version: '3'
services: 
    java: 
        build: 
            dockerfile: ./Dockerfile
            context: .
        volumes: 
            - .:/Java/
        env_file: 
            - ./.env
        stdin_open: true
        tty: true